name: Release

on:
  push:
    branches:
      - main
    tags:
      - v*

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      
      - name: Setup bun
        uses: oven-sh/setup-bun@v1
      
      - name: Build
        run: make build
